services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: warden
      POSTGRES_PASSWORD: warden
      POSTGRES_DB: warden
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: